---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    - name: Create molecule instance(s)
      lxd_container:
        name: "{{ item.name }}"
        state: started
        source:
          type: "{{ item.source.type | default('image') }}"
          mode: "{{ item.source.mode | default('pull') }}"
          server: >-
            {{ item.source.server |
               default('https://images.linuxcontainers.org') }}
          protocol: "{{ item.source.protocol | default('lxd') }}"
          alias: "{{ item.source.alias }}"
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600
      loop: "{{ molecule_yml.platforms }}"
