---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
  tasks:
    - name: Destroy molecule instance(s)
      lxd_container:
        name: "{{ item.name }}"
        state: absent
        force_stop: "{{ item.force_stop | default(true) }}"
      loop: "{{ molecule_yml.platforms }}"

    - name: Delete host_vars each host directory
      file:
        path: >-
          {{ (molecule_yml.provisioner.inventory.links.host_vars
              ~ '/' ~ item.name) | realpath }}
        state: "absent"
      loop: "{{ molecule_yml.platforms }}"
