---
dependency:
  name: galaxy

driver:
  name: lxd

lint: |
  set -e
  ansible-lint ${ROLE_DIR}

provisioner:
  name: ansible
  playbooks:
    create: ${CREATE_YML}
    destroy: ${DESTROY_YML}
    converge: ${CONVERGE_YML}
  optoins:
    diff: true
  inventory:
    links:
      host_vars: ${HOST_VARS}
      group_vars: ${GROUP_VARS}

verifier:
  name: testinfra
  directory: ${TESTINFRA_DIR}
  options:
    s: true  # pytest の -s を有効化. テスト時に print() の標準出力結果を見るため.
    v: true
