---
dependency:
  name: galaxy

driver:
  name: lxd

lint: |
  set -e
  ansible-lint ${ROLE_DIR:-../}

provisioner:
  name: ansible
  playbooks:
    create: ${CREATE_YML:-../common/playbooks/create.yml}
    destroy: ${DESTROY_YML:-../common/playbooks/destroy.yml}
    converge: ${CONVERGE_YML:-../common/playbooks/converge.yml}
  optoins:
    diff: true
  inventory:
    links:
      group_vars: group_vars

verifier:
  name: testinfra
  directory: ${TESTINFRA_DIR:-../common/tests}
  options:
    s: true  # pytest の -s を有効化. テスト時に print() の標準出力結果を見るため.
    v: true
